version: '2'
services:
  app:
    build: .
    ports:
    - "8080:80"

  db:
    image: mysql:5.7
    env_file: .env

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
